### ISSUE TITLE
commands within \edtext

### ISSUE THREAD

**Issue by floriandk** [stenskjaer/samewords#7] opened 2017-07-10 14:22 UTC
Commands inside the `\edtext{…}` like 

```latex
\documentclass{article}
\usepackage{polyglossia,fontspec,xunicode}
\setmainlanguage{latin}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\begin{document}

\beginnumbering
\pstart

\edtext{Hákon\emph{ar} konungs}{\Afootnote{k\emph{on}gſ \msside{33b} hakon\emph{ar} Sk}}, 

\pend
\endnumbering

\end{document}

```
make `samewords` abort with 

```
Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/samewords/cli.py", line 31, in main
    print(samewords.core.process_document(filename))
  File "/usr/local/lib/python3.6/site-packages/samewords/core.py", line 14, in process_document
    updated_paragraphs = [annotate.critical_note_match_replace_samewords(par) for par in paragraphs]
  File "/usr/local/lib/python3.6/site-packages/samewords/core.py", line 14, in <listcomp>
    updated_paragraphs = [annotate.critical_note_match_replace_samewords(par) for par in paragraphs]
  File "/usr/local/lib/python3.6/site-packages/samewords/annotate.py", line 714, in critical_note_match_replace_samewords
    result = sub_processing(TextSegment(text))
  File "/usr/local/lib/python3.6/site-packages/samewords/annotate.py", line 698, in sub_processing
    if search_in_proximity(search_word, context.before, context.after):
  File "/usr/local/lib/python3.6/site-packages/samewords/annotate.py", line 455, in search_in_proximity
    if re.search(r'\b' + search_word + r'\b', maintext_words):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 856, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \e at position 7

```

As a starting point I'd suggest that unknown commands could be compared as if they were text. If one word is e.g. emphasised and the other not, I suppose that this would enough differentiation when both occur in the apparatus, wouldn't it?

On the other hand also some other standard commands like`\index` give the same problem. In most real life cases typical candidates for the `\sameword`-mark will also have the same index markup. But it is easy to imagine cases when e.g. the same frequent name refers to two different persons, which will need different index-entries. If both occur in the apparatus, though, we'd need sameword-numbers anyway.

As it is very difficult to know what anybody will need in the next edition, I'd like to suggest that `samewords` will also compare commands as text (e.g. `Hákon\emph{ar}` and `Hákonar` will be treated as different words) but to allow for a negative list, so that I could ask for e.g. `\index` be ignored and `Hákonar\index{Håkon I}` and `Hákonar\index{Håkon II}` be tagged as `\sameword{Hákonar}\index{Håkon I}` and `\sameword{Hákonar}\index{Håkon II}`.
Would this be feasible?

**Comment by stenskjaer** [comment] 2017-07-17 21:04
Okay. A solution to this is just around the corner. 
Actually the script generally ignores all macros, the way you suggest. It is therefore not really relevant to actually make it possible to let the user add custom macros that should be included in disambiguation and matching, as that already is the case. 

For example, this passage:
```latex
\edtext{Sortes\test{1}}{\Afootnote{Socrates B}} dicit: Sortes\test{2} probus
```
Will result in a search for "Sortes1" in the string "dicit Sortes2 probus", which will not succeed. 

On the other hand, this passage:
```latex
\edtext{Sortes\test{1}}{\Afootnote{Socrates B}} dicit: Sortes\test{1} probus
```
Will result in a search for "Sortes1" in the string "dicit Sortes1 probus", which will succeed and therefore annotate the instances.

I am adding a possibility of defining commands that should be kept in text, so that the user can choose to let `Hákon\emph{ar}` and `Hákonar` be two different strings. I will push some of these changes very soon, and let you know so that you can test it when you get a chance.

**Comment by stenskjaer** [comment] 2017-07-18 08:52
When you get a chance, could you please test the branch [issue-8](https://github.com/stenskjaer/samewords/tree/issue-8)? I have added some directions to how to test a branch in the readme of the branch, so please let me know if that is enough to make it work. 

I have also added some attempts at describing the added arguments for giving custom included and excluded macros. I would like to know if that makes sense too.

This problem is connected with issue #7, so you can test that at the same time.

**Comment by floriandk** [comment] 2017-07-31 20:23
Sorry I've kept you waiting!

Generally using commands inside `\edtext` and modifing the behaviour with `--include-macros` works for me.

But unfortunately I can't get `--exclude-macros`to work. E.g.:

```latex
\documentclass{article}
\usepackage{polyglossia,fontspec,xunicode}
\setmainlanguage{latin}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\newcommand{\somemacro}[1]{}

\begin{document}

\beginnumbering
\pstart
Han var sonr \edtext{Hákon\emph{ar}\somemacro{Håkon II} konungs}{\Afootnote{k\emph{on}gſ hakon\emph{ar} Sk}}, sons Hákonar\somemacro{Håkon I} konungs
\pend
\endnumbering

\end{document}
```

run with `samewords testinexclude.tex --exclude-macros excl.tex --output testinexclude-SW.tex` and a file `excl.tex` only containing the line `\somemacro` gives me:

```python
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 363, in content
    symbol = search_string[position]
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    load_entry_point('samewords', 'console_scripts', 'samewords')()
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/cli.py", line 61, in main
    output_content = samewords.core.process_document(filename)
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/core.py", line 14, in process_document
    updated_paragraphs = [annotate.critical_note_match_replace_samewords(par) for par in paragraphs]
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/core.py", line 14, in <listcomp>
    updated_paragraphs = [annotate.critical_note_match_replace_samewords(par) for par in paragraphs]
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 772, in critical_note_match_replace_samewords
    result = sub_processing(TextSegment(text))
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 759, in sub_processing
    context.before, context.after, search_word)
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 545, in replace_in_proximity
    left = replace_in_context_list(context_before_list, search_word)
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 540, in replace_in_context_list
    chunk = replace_in_string(word, chunk)
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 643, in replace_in_string
    updated_replacement = make_replacements(search_word_listed, replacement_string_listed)
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 620, in make_replacements
    match_in_replace_list = check_list_match(search_list, replace_list, return_list=[])
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 597, in check_list_match
    if re.search(r'(?<!\w)' + re.escape(clean(pattern_list[0])) + '(?!\w)', clean(replace_list[0])):
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 474, in clean
    position += len(macro.complete_macro())
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 409, in complete_macro
    + '{' + Brackets(self.input_string, start=position).content + '}'
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 325, in __init__
    self.content = self.content(search_string, start, macro)
  File "TeX-testing/sameword-test/samewords-issue-8/samewords/annotate.py", line 375, in content
    raise ValueError("Unbalanced brackets. The provided string terminated before all "
ValueError: Unbalanced brackets. The provided string terminated before all brackets were closed.
```

Am I doing this correctly?

**Comment by stenskjaer** [comment] 2017-08-01 21:09
First: Thanks for all these great reports! This one turns out to be more hairy than expected, so I'm still stuck at this.

First problem is the following: In *reledmac* not any (actually very few) macros will be accepted inside a `\sameword{}` macro. This means that although we can implement a solution where multiword sameword entries can contain (different) macros based on our included and excluded macros (just like in your example), it still won't accept it during compilation.

For example, when we get the correct output from your example sentence, the document would look like this (I have added linebreaks for readability):
```tex
\documentclass{article}
\usepackage{polyglossia,fontspec,xunicode}
\setmainlanguage{latin}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\newcommand{\somemacro}[1]{}

\begin{document}

\beginnumbering
\pstart
Han var sonr 
\edtext{\sameword[1]{Hákon\emph{ar}\somemacro{Håkon II} konungs}}%
  {\Afootnote{k\emph{on}gſ hakon\emph{ar} Sk}}%
, sons \sameword{Hákonar\somemacro{Håkon I} konungs}
\pend
\endnumbering

\end{document}
```

But since `\somemacro{}` is not allowed inside `\sameword{}`, it will return this error:
```
! Use of \\sameword doesn't match its definition.
\text@command #1->\def \reserved@a {
                                    #1}\ifx \reserved@a \@empty \let \check@...
l.17 ...footnote{k\emph{on}gſ hakon\emph{ar} Sk}}
                                                  , sons \sameword{Hákonar\...
```

For the implementation in reledmac, see https://github.com/maieul/ledmac/issues/661.

So we need to think about how we would solve this. 
We try to get `\sameword` to accept arbitrary macros, but I suspect that it might be difficult, and that Maieul wouldn't be a big fan of the idea.

But we still want the samewords command to contain these macros, as we cannot move them. This is only a problem with multi-word sameword annotations. 

I don't know if you have any thoughts?

**Comment by stenskjaer** [comment] 2017-08-01 21:33
Woops! Sorry about that guys. Seems I'm haven't remembered to update my packages, so it is actually not a problem. 
Alarm is off for now. My bad!

I'm going to bed now, but I will get back to this tomorrow night.

**Comment by maieul** [comment] 2017-08-01 21:34
maybe I could add an tool to define an arbitrary list of macro which could be allowed in sameword. But as it could be macro with one or more argument, the user should have to do it own \let command.

For example you should have to do

\apptocmd{\sameword@noexpands}{
\let\macro\relax
}

**Comment by stenskjaer** [comment] 2017-08-02 08:05
Very interesting suggestion. Since, as you mention in the reledmac issue, that it only affects font manipulating commands, I wonder how big the problem is (as I said, the previous post on my part was mistaken, as I hadn't updated on the machine I tested it, :-/). 

On the other hand I do personally think that it is better to provide a solution to a problem that may arise than let the user run his head against a wall on it, search google to no avail and then just maybe post an issue ticket for a fix.

It definitely is an edge case scenario: multi-word sameword annotations containing custom named font manipulating commands. If you are in that situation and really need a different name for your `\emph{}` command, maybe it is also not unfair to expect of you to use `\let` in the definition of the custom exception for `\sameword`. As long as it is explained how you should declare the exception in the documentation. 

But as I see it, this would not be an urgent feature.

P.S. Should I add an issue in the reledmac repo?

**Comment by maieul** [comment] 2017-08-02 08:22
yes you should open an issue

**Comment by floriandk** [comment] 2017-08-02 09:15
I actually think the problem is not quite as exotic...

One thing are custom commands:
Personally I often use semantic markup with self-defined macros. So these would be nice-to-have. But if they aren't technically possible or @maieul decides this isn't a priority, I could do some automatic preprocessing (e.g. `\abbr{}` -> `\emph{}` etc.) before I run `samewords` and typeset.

But there are some standard commands that I think are crucial to be allowed in `\sameword{}`. First thing I think of is indexing e.g.

```latex
\documentclass{article}
\usepackage{polyglossia,fontspec,xunicode}
\setmainlanguage{latin}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\usepackage{makeidx}
\makeindex

\begin{document}

\beginnumbering
\pstart
Han var sonr 
\edtext{\sameword[1]{Hákon\emph{ar}\index{Håkon II} konungs}}%
  {\Afootnote{k\emph{on}gſ hakon\emph{ar} Sk}}%
, sons \sameword{Hákonar\index{Håkon I} konungs}
\pend
\endnumbering

\end{document}
```

doesn't compile with the up to date `reledmac`. The same goes for `polyglossia`'s language-switching commands in the same places.

I'd be really happy if these would work out of the box -- and I guess I won't be the only one :)

**Comment by maieul** [comment] 2017-08-02 09:34
you can open an issue with the standard command you think should be included

**Comment by stenskjaer** [comment] 2017-08-07 12:36
Phew, this was a really tough one. I have pushed some updates to the [issue-8 branch](https://github.com/stenskjaer/samewords/tree/issue-8). If you could maybe give it a spin and see if the inclusion and exclusion works as you would expect?

**Comment by stenskjaer** [comment] 2017-08-17 17:43
Any chance to test this?

**Comment by stenskjaer** [comment] 2017-09-04 06:30
I'm closing this now. I believe it works. But if someone should feel like testing the branch, go ahead.

**Closed by stenskjaer** 2017-09-04 06:30 UTC

**Comment by floriandk** [comment] 2017-09-12 10:39
Sorry for the late reply, but there still seems to be one glitch:

```latex
\documentclass{article}
\usepackage{polyglossia,fontspec,xunicode}
\setmainlanguage{latin}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\newcommand{\test}[1]{}


\begin{document}

\beginnumbering
\pstart
\edtext{Sortes\test{1}}{\Afootnote{Socrates B}} dicit: Sortes\test{2} probus
\pend
\endnumbering

\end{document}
```

the issue8-branch with `--exclude-macros` and the macro `\test` in the exclude-file gives me 

```latex
\documentclass{article}
\usepackage{polyglossia,fontspec,xunicode}
\setmainlanguage{latin}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup]{reledmac}

\newcommand{\test}[1]{}


\begin{document}

\beginnumbering
\pstart
\edtext{\sameword[1]{Sortes\test{1}}}{\Afootnote{Socrates B}} dicit: \sameword{Sortes\test{2} probus
\pend}
\endnumbering

\end{document}
```

obviously with the closing bracket of the second `\sameword`-tag at the wrong place.

**Comment by floriandk** [comment] 2017-09-12 10:43
As for the readme, I would suggest to call the custom-command used as an example for `--exclude-macros` something else than `\pagebreak{}` as this is a standard LaTeX-command. Perhaps call it `\msbreak{}`?
