### ISSUE TITLE
two occurences within the same edtext

### ISSUE THREAD

**Issue by floriandk** [stenskjaer/samewords#30] opened 2018-05-07 17:56 UTC
I am not sure whether this actually _is_ a problem or might even be handled like this on purpose. But let me put it here anyway, just in case:

```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
two dollars and
\edtext{two \edtext{cent}{%
	\Afootnote{dimes}}
and even two more}{%
	\lemma{two–more}%
	\Afootnote{del.}},
and two more.
\pend
\endnumbering

\end{document}
```

is converted to

```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{two} dollars and
\edtext{\sameword[1]{two} \edtext{cent}{%
	\Afootnote{dimes}}
and even two \sameword[1]{more}}{%
	\lemma{\sameword{two}–\sameword{more}}%
	\Afootnote{del.}},
and \sameword{two} \sameword{more}.
\pend
\endnumbering

\end{document}
```

This compiles to the correct endresult in `reledmac` but I am wondering about why "and even two " isn't tagged… Is that by design?

I haven't yet been able to construct an example where this exception results in a faulty end-result: When another `\edtext{two}`, e.g. in the next sentence, is added, also the earlier one will receive a `\sameword{}` command. Could there be other cases where this will not work?

**Comment by stenskjaer** [comment] 2018-05-07 20:00
This is actually on purpose...
When you have a lemma with the first and last word, those are the only ones that will appear in the apparatus entry. And therefore the only ones that will need disambiguation.

If you didn't have a lemma, the whole expression would be wrapped in `\sameword{}` and then there would also not be a need for disambiguation (in this specific case) because there is not duplicate of that whole phrase in the context.

I'm not sure I understand the last paragraph, so if I haven't answered that, maybe you could elaborate that a bit?

**Comment by floriandk** [comment] 2018-05-07 20:26
Oh yes, that makes sense! Thanks for the explanation.

The last paragraph was only a speculation whether there might be cases where it could be a problem. One of my test was to change the example to 

```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
two dollars and
\edtext{two \edtext{cent}{%
	\Afootnote{dimes}}
and even two more}{%
	\lemma{two–more}%
	\Afootnote{del.}},
and 
\edtext{two}{%
	\Afootnote{three}}
 more.
\pend
\endnumbering

\end{document}
```

to see whether this would work. As you know it does:

```latex
\documentclass{article}

\usepackage[series={A},nofamiliar,noeledsec,noledgroup,draft]{reledmac}

\begin{document}

\beginnumbering
\pstart
\sameword{two} dollars and
\edtext{\sameword[1]{two} \edtext{cent}{%
	\Afootnote{dimes}}
and even \sameword{two} \sameword[1]{more}}{%
	\lemma{\sameword{two}–\sameword{more}}%
	\Afootnote{del.}},
and 
\edtext{\sameword[1]{two}}{%
	\Afootnote{three}}
 \sameword{more}.
\pend
\endnumbering

\end{document}
```

So this issue is thankfully superfluous 👍

**Closed as completed** 2018-05-07 20:40 UTC
